name: minify

on: 
  push:
   branches:
      - main

  pull_request:
     branches:
      - main


jobs:
  minify:
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'  

      - name: Install minify
        run: npm install minify -g

      - name: Minify JavaScript
        run: minify main.js > main.min.js

      - name: Commit minified file
        uses: stefanzweifel/git-auto-commit-action@v5
        
        with:
          commit_message: "Minify Listo"
